# Generated by Django 2.2.2 on 2019-06-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_avatar_url',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
