# Generated by Django 2.2.2 on 2019-06-24 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_user_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_avatar_url',
        ),
    ]
