# Generated by Django 2.2.2 on 2019-06-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_remove_comment_user_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_avatar_url',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
