# Generated by Django 2.2.2 on 2019-06-24 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_comment_user_avatar_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_avatar_url',
            new_name='user_avatar',
        ),
    ]
