# Generated by Django 2.2.2 on 2019-06-24 03:09

import article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_articlepost_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='author_avator',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='articlepost',
            name='content_img',
            field=models.ImageField(default='', upload_to=article.models.upload_to),
        ),
    ]
