# Generated by Django 2.2.2 on 2019-06-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190624_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='catagory',
            field=models.CharField(default='', max_length=100),
        ),
    ]
