# Generated by Django 2.2.2 on 2019-06-24 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_articlepost_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepost',
            old_name='author_avator',
            new_name='author_avatar',
        ),
    ]
