# Generated by Django 2.2.2 on 2019-06-25 06:45

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20190624_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='body',
            field=DjangoUeditor.models.UEditorField(verbose_name='内容'),
        ),
    ]
