# Generated by Django 2.0.8 on 2019-06-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20190625_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='brief',
            field=models.CharField(default='', max_length=500),
        ),
    ]
